### ISSUE TITLE
IMPORTANT FIX NEEDED

### ISSUE THREAD

**Issue by idk-pixel** [Sank6/Discord-Bot-List#158]
Hey! When someone adds a bot other users can see it if they have bot id, make it so only user and admins can see it

**Comment by idk-pixel** [comment]
Also another security issue..
![image](https://user-images.githubusercontent.com/63606830/91364432-4d04fc00-e7c4-11ea-941b-57261bffaf71.png)
make a thing where you can refresh this access_token, it allows people to access other peoples accounts in the list....

**Comment by Sank6** [comment]
> Hey! When someone adds a bot other users can see it if they have bot id, make it so only user and admins can see it
Yes, that's not an issue. It's intentional. Bots aren't completely "hidden", they're only removed from the list, so people don't "stumble upon" unverified bots.

And that isn't a security issue. There's no way someone can access someone else's account unless their access token was compromised. And the access token can be refreshed and will be refreshed automatically. I should probably use `discord-passport` though
