### ISSUE TITLE
Redirect user to previous page instead of /me after login 

### ISSUE THREAD

**Issue by shootdot** [Sank6/Discord-Bot-List#318]
Hey,
I am not much familiar with OAuth2. But please make this thin it would be much better.
Auto join user to the server when he log's in via discord & When user log's in redirect to the page where he was it always redirects to ```/me```

**Comment by Sank6** [comment]
I had a look at it before. The problem is you have to ask the user for permission to join servers for them in the login screen and I don't think that's necessary. I've tried to include only scopes which are completely necessary which is just the username part. Just an invite link to the server works fine imo.

**Comment by shootdot** [comment]
@Sank6 What about redirect to the  page where the user was instead of redirecting to ```/me``` ?

**Comment by Sank6** [comment]
Oh I didn't see that. Yeah I'll see.

**Comment by Sank6** [comment]
Added
