### ISSUE TITLE
Switch to react  😳 ?

### ISSUE THREAD

**Issue by exiify** [Sank6/Discord-Bot-List#407]
I think Switching to react will make it easier to mannage

**Comment by Sank6** [comment]
True 😅. If I were to rewrite this in it's entirety, I would use Typescript and a JS framework, probably next.js or react. I'm not saying that It would basically require a whole restart and maybe even a new repo because the code would be entirely different.
The reason I haven't already done this is because I don't use this myself. I used to actually host it and use it. Then I stopped and decided to make it open sourced and see where it goes.
I don't plan to rewrite this any time soon though
